global:
  resolve_timeout: 30s

route:
  group_by: ['...']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 10m
  receiver: 'AllRec'

receivers:
  - name: 'AllRec'
    email_configs:
      - to: 'youremail@xyz.com'
        from: 'PromServer@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'your username/email'
        auth_password: 'your email password (2FA)'
        send_resolved: true

#  - name: 'slack-notifications'
    slack_configs:
    - channel: 'alerts'
      api_url: 'https://slackapiurl.com'
      send_resolved: true
      icon_url: 'https://avatars3.githubusercontent.com/u/3380462'  # Added single quotes around the URL
      title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
          {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
            {{" "}}(
            {{- with .CommonLabels.Remove .GroupLabels.Names }}
              {{- range $index, $label := .SortedPairs -}}
                {{ if $index }}, {{ end }}
                {{- $label.Name }}="{{ $label.Value -}}"
              {{- end }}
            {{- end -}}
            )
          {{- end }}
      text: >-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

          *Description:* {{ .Annotations.description }}

          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
                                                                                                                                        54,39         Bot
